- name: Install Docker and deploy app
  hosts: all
  become: true

  vars:
    app_dir: /home/ubuntu/app

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        usermod -aG docker ubuntu

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        mode: "0755"

    - name: Copy docker-compose.yml
      copy:
        src: ../../docker-compose.yml
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: ubuntu
        mode: "0644"

    - name: Login to AWS ECR
      shell: |
        export AWS_ACCESS_KEY_ID={{ aws_access_key_id }}
        export AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}
        export AWS_DEFAULT_REGION={{ aws_region }}
        aws ecr get-login-password | docker login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com

    - name: Run Docker Compose
      shell: |
        export AWS_ACCOUNT_ID={{ aws_account_id }}
        export AWS_REGION={{ aws_region }}
        export NODE_REPO_NAME={{ node_repo_name }}
        export NGINX_REPO_NAME={{ nginx_repo_name }}
        cd {{ app_dir }}
        docker compose pull
        docker compose up -d
